config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  get 'query/' => 'query#index', as: :query
  get 'i/' => 'subject#index', as: :subject

  mount Facebook::Messenger::Server, at:"bot"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fact.rb
class Fact < ActiveRecord::Base

end

app/models/new.rb
class New < ActiveRecord::Base

end

app/models/story.rb
class Story < ActiveRecord::Base

end

app/models/subject.rb
class Subject < ActiveRecord::Base

end

app/models/wild_new.rb
class WildNew < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/check_text.rb
def check_text()
	#export GOOGLE_APPLICATION_CREDENTIALS="My Project 13107-47d62a59880a.json"

	# Imports the Google Cloud client library
	#require "google/cloud/language"

	# Instantiates a client
	language = Google::Cloud::Language.new

	# The text to analyze
	text = "Hello, world!"

	# Detects the sentiment of the text
	response = language.analyze_sentiment content: text, type: :PLAIN_TEXT

	# Get document sentiment from response
	sentiment = response.document_sentiment

	puts "Text: #{text}"
	puts "Score: #{sentiment.score}, #{sentiment.magnitude}"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index; end

end

app/controllers/query_controller.rb
class QueryController < ApplicationController


  def index

    text = get_text(params[:query])
    news_list = NewsService.get_news
    facts_list = FactsService.get_facts

    story = NLPService.check_content(text, news_list, facts_list)

    if story.present? and story != 'to do'
      if story.is_a? Fact
        if story.fake
          result_image = get_image(NLPService::CHECK_RESPONSE[:fake])
          @true_or_fake = "É Fake!"
        else
          @true_or_fake = "É Verdade!"
          result_image = get_image(NLPService::CHECK_RESPONSE[:fact])
        end
      else
        result_image = get_image(NLPService::CHECK_RESPONSE[:news])
        @true_or_fake = "Não sabemos afirmar"
      end
      @link = story.link
    else
      result_image = get_image(NLPService::CHECK_RESPONSE[:dunno])
      @true_or_fake = "Nao encontramos nada =/ Mas te avisamos quando encontrar!"
      @link = nil
    end

    render locals: {
      true_or_fake: @true_or_fake,
      link: @link,
      result_image: result_image
    }

  end

  private

  def get_image(code)
    NLPService::CHECK_RESPONSE.each do |k, v|
      if v == code
        return  k.to_s
      end
    end
  end

  def get_text(query)

    if query.strip =~ /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix
      require 'open-uri'

      begin
        html = Nokogiri::HTML(open(query))

        html.xpath('//p').text
      rescue
        raise ActionController::RoutingError.new('Not Found') if Rails.env.development?
        redirect_to root_url
      end
    else
      query
    end
  end

end

app/controllers/subject_controller.rb
class SubjectController < ApplicationController

  def index

    subjects = Subject.all # Subject.where(id:
    #  WildNew.all.count('*').group(:subject_id).order('count DESC').pluck(:subject_id))

    render locals: {
      subjects: subjects
    }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<script>
  location.href = 'https://m.me/detetive-bot';
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Detetive Digital <%= (@true_or_fake.present? ? " - #{@true_or_fake}" : '') %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= yield :meta_tags %>
  </head>

  <body>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.12&appId=213647759410490&autoLogAppEvents=1';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <%= yield %>
  </body>
</html>

app/views/query/index.html.erb
<% content_for :meta_tags do %>
  <% if result_image.present? %>
    <meta property="og:url"                 content="<%= query_url( query: params[:query] ) %>" />
    <meta property="og:type"                content="website" />
    <meta property="og:title"               content="Detetive Digital - <%= true_or_fake %>" />
    <meta property="og:description"         content="<%= (link.present? ? "Você pode encontrar mais informações nesse link: #{link}" : "Te avisamos mesmo, é sério!") %>" />
    <meta property="og:image:type"          content="image/jpeg" />
    <meta property="og:image:width"         content="480" />
    <meta property="og:image:height"        content="360" />
    <meta property="og:image"               content="<%= image_url "#{result_image}.jpg" %>" />
    <meta property="og:image:secure_url"    content="<%= image_url "#{result_image}.jpg" %>" />
  <% end %>
<% end %>

<div class="query-area">
  <h1><%= true_or_fake %></h1>
  <%= image_tag "#{result_image}.jpg" %>
  <% if link.present? %>
    <p>
      <h4>Você pode encontrar mais informações nesse link: </h4>
      <%= link_to link, link %>
    </p>
  <% end %>
  <div class="fb-button-row">
    <div class="fb-share-button" data-href="<%= query_url( query: params[:query] ) %>" data-layout="button" data-size="large" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=<%= query_url( query: params[:query] ) %>&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Compartilhar</a></div>
  </div>
</div>

app/views/subject/index.html.erb
<div class="subject-area">

  <table>
    <tr>
      <th class="text-center">
        Assuntos mais falados e ainda não checkados:
      </th>
    </tr>
    <!-- < % subjects.each do |subject| %>
      <tr>
        <td> < %= subject.title %> </td>
      </tr>
    < % end %> -->
    <tr>
      <td>
        Estátua da Pablo Vittar vai substituir o Cristo Redentor
      </td>
    </tr>
    <tr>
      <td>
        O Próximo inverno do Rio vai ser o mais rigoroso dos últimos 100 anos
      </td>
    </tr>
  </table>

</div>